#!/bin/bash
#
# deploy-mcp.sh
#
# Script de deploy do MCP Server do QA Agent.
# 1. Gera o bundle transpilado (dist/mcp/index.js)
# 2. Atualiza o wrapper /tmp/qa-agent-mcp-wrapper.sh
# 3. Torna o wrapper executável
#
# Uso:
#   bash scripts/deploy-mcp.sh
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DIST_MCP_DIR="${PROJECT_ROOT}/dist/mcp"
WRAPPER_PATH="/tmp/qa-agent-mcp-wrapper.sh"

echo "[deploy-mcp] Building MCP server bundle…"
cd "${PROJECT_ROOT}"

# 1. Build do MCP
bun run build:mcp

# 2. Wrapper auto-gerado
cat > "${WRAPPER_PATH}" <<EOF
#!/bin/bash
# MCP QA Agent Wrapper
# Launches the qa-agent MCP server with Playwright config.
# AUTO-GENERATED by scripts/deploy-mcp.sh — do not edit manually.

export PATH="/home/crislerwintler/.bun/bin:$PATH"
export PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH="/home/crislerwintler/.cache/ms-playwright/chromium-1200/chrome-linux64/chrome"
export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD="1"

exec bun ${PROJECT_ROOT}/dist/mcp/index.js "\$@"
EOF

chmod +x "${WRAPPER_PATH}"

echo "[deploy-mcp] ✅ Wrapper atualizado: ${WRAPPER_PATH}"
echo "[deploy-mcp] ✅ Entry point: ${DIST_MCP_DIR}/index.js"
echo "[deploy-mcp] ✅ Pronto para uso! Para ativar, reinicie o Hermes."
